language: python

python:
  # - "3.4"
  # - "3.3"
  - "2.7"
  # - "2.6"
  # - "pypy"

services:
  - mysql

before_script:
  - mysql -e 'create database test;'

install: pip install -r requirements.txt

script: ./runtests.py
