sudo: required

notifications:
  email: false
  webhooks: https://coveralls.io/webhook?repo_token=7l8yKtg4su0M31T0eGIaM0tnjvH0Rd5PM

language: python
python: '3.5'
cache: pip

env:
  global:
    - COVERALLS_PARALLEL=true
  matrix:
    - "DB=mysql DB_VERSION=5.5"
    - "DB=mysql DB_VERSION=5.6"
    - "DB=mysql DB_VERSION=5.7"
    - "DB=mariadb DB_VERSION=5.5"
    - "DB=mariadb DB_VERSION=10.0"
    - "DB=mariadb DB_VERSION=10.1"

before_script: .travis/before_script.sh

install:
  - pip install coveralls tox

script:
  - coverage erase
  - tox

after_success:
  - coverage combine
  - coveralls
